#!/bin/bash

#$ -cwd
#$ -j y
#$ -q node0
#$ -pe mpich 40
#$ -S /bin/bash

PREFIX=Skeletonema_MiSeq_20151016
ASSEMBLY=${PREFIX}_novo.fa
MAPPING=/state/partition2/tmp/${PREFIX}.cas
FILE1=/nobackup/data5/Skeletonema_marinoi_genome_project/data/S1-M_S2_L001_R1_001.FQF.Pair.fastq
FILE2=/nobackup/data5/Skeletonema_marinoi_genome_project/data/S1-M_S2_L001_R2_001.t-20.FQT.Pair.fastq
FILE3=/nobackup/data5/Skeletonema_marinoi_genome_project/data/S1-M_S2_L001_R1_001.FQF.Singles.fastq
FILE4=/nobackup/data5/Skeletonema_marinoi_genome_project/data/S1-M_S2_L001_R2_001.t-20.FQT.Singles.fastq
LOG=${PREFIX}.log
ERR=${PREFIX}.err.log
DIST=${PREFIX}.dist
#CPU=48

export TMPDIR=/state/partition2/tmp

#date >> $LOG
#echo "Starting clc_assembly analysis" >> $LOG
#time clc_assembler -v -w 64 -e $DIST --cpus $NSLOTS -o $ASSEMBLY -p fb ss 100 450 -q -i $FILE1 $FILE2 -q $FILE3 $FILE4 >> $LOG 2>> $ERR

date >> $LOG
echo "Starting clc_mapper analysis" >> $LOG
time clc_mapper --cpus $NSLOTS -o $MAPPING -p fb ss 100 450 -q -i $FILE1 $FILE2 -q $FILE3 $FILE4 -d $ASSEMBLY >> $LOG 2>> $ERR

date >> $LOG
echo "Starting clc_mapping_info analysis" >> $LOG
time clc_mapping_info -c -n $MAPPING > ${PREFIX}_mapping_info.txt

#date >> $LOG
#echo "Starting clc_sequence_info analyses" >> $LOG
#time clc_sequence_info -l -k -n $ASSEMBLY > ${PREFIX}_seqInfo.txt
#time clc_sequence_info -l -k -n -c 1000 $ASSEMBLY > ${PREFIX}_seqInfo-1000.txt
#time clc_sequence_info -l -k -n -c 2000 $ASSEMBLY > ${PREFIX}_seqInfo-2000.txt
#time clc_sequence_info -l -k -n -c 5000 $ASSEMBLY > ${PREFIX}_seqInfo-5000.txt
#time clc_sequence_info -l -k -n -c 10000 $ASSEMBLY > ${PREFIX}_seqInfo-10000.txt
