#!/bin/bash

#$ -cwd
#$ -q high_mem
#$ -S /bin/bash

# Script for submitting fastq_quality_trimmer analyses on Albiorix. 
# Second argument for the script is passed to the -t flag wich sets 
# the quality trimming cut-off value. This value is alos included in 
# the output filename. The script ends with a fastqc analysis of the 
# resulting fastq file.

# Usage: qsub fastq_quality_trimmer.sge <fastq file> <int>


ERROR=${PWD##*/}.err

fastq_quality_trimmer -Q33 -t $2 -i $1 -o "${1%.fastq}.t-${2}.FQT.fastq" 2>> $ERROR
fastqc "${1%.fastq}.FQT.fastq"
