#$ -cwd
#$ -q Annotation-3
#$ -S /bin/bash
#$ -pe mpich 20

module load SGA/v0.10.15

FILE1=/proj/data5/data/skeletonema/reads/A.Blomberg_17_16-P8511/01-QC/P8511_101/fastq_trimmed/P8511_1_10M.fastq
FILE2=/proj/data5/data/skeletonema/reads/A.Blomberg_17_16-P8511/01-QC/P8511_101/fastq_trimmed/P8511_2_10M.fastq
PREPROCESSED=Sm_A.Blomberg_17_16-P8511.preprocessed.fastq
GENOME=Sm_A.Blomberg_17_16-P8511.preprocessed.preqc

sga preprocess --pe-mode 1 $FILE1 $FILE2 > $PREPROCESSED
sga index -a ropebwt --no-reverse -t $NSLOTS $PREPROCESSED
sga preqc -t $NSLOTS $PREPROCESSED > $GENOME
sga-preqc-report.py $GENOME /usr/local/packages/sga-0.10.15/src/examples/preqc/*.preqc
