#$ -cwd
#$ -pe mpich 10
#$ -q node0
#$ -S /bin/bash

DB=/nobackup/data5/Skeletonema_marinoi_genome_project/test/MiSeq_data/20151105/Skeletonema_MiSeq_20151105_novo.fa
FWD=/nobackup/data5/data/skeletonema/reads/1_130918_AC2D94ACXX_P704_106_dual28_1.FXT.CA.FQF.Pair.fastq
REW=/nobackup/data5/data/skeletonema/reads/1_130918_AC2D94ACXX_P704_106_dual28_2.FXT.CA.FQF.Pair.fastq

mapping_filtering.sh -d $DB -1 $FWD -2 $REW -n 300_lib -k -t $NSLOTS

